version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
    ignore:
      - dependency-name: "Microsoft.NET.ILLink.Tasks"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
